catalog
catalogChangeLog
		
 ^ 
'- Version 1.0.4
[[[
(ConfigurationOfMessagePack project version: ''1.0.4'') load
]]]
- Version 1.2.2
[[[
(ConfigurationOfMessagePack project version: ''1.2.2'') load
]]]
- Version 1.2.3
[[[
(ConfigurationOfMessagePack project version: ''1.2.3'') load
]]]
- Version 1.2.4
[[[
(ConfigurationOfMessagePack project version: ''1.2.4'') load
]]]
- Version 1.2.5
[[[
(ConfigurationOfMessagePack project version: ''1.2.5'') load
]]]
- Version 1.2.9a
Timestamp(DateAndTime) supported.
[[[
(ConfigurationOfMessagePack project version: ''1.2.9a'') load
]]]
- Version 1.3.0
Fixed & Optimized string encoding 
[[[
(ConfigurationOfMessagePack project version: ''1.3.0'') load
]]]
'