catalog
catalogChangeLog
		
 ^ 
'- Version 1.0.4
[[[
(ConfigurationOfMessagePack project version: ''1.0.4'') load
]]]
- Version 1.2.2
[[[
(ConfigurationOfMessagePack project version: ''1.2.2'') load
]]]
- Version 1.2.3
[[[
(ConfigurationOfMessagePack project version: ''1.2.3'') load
]]]
- Version 1.2.4
[[[
(ConfigurationOfMessagePack project version: ''1.2.4'') load
]]]
- Version 1.2.5
[[[
(ConfigurationOfMessagePack project version: ''1.2.5'') load
]]]
- Version 1.2.9
Timestamp(DateAndTime) supported.
[[[
(ConfigurationOfMessagePack project version: ''1.2.9'') load
]]]
'